//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stories
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public System.Guid SourceId { get; set; }
        public System.Guid PhotoId { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual Sources Sources { get; set; }
    }
}
