//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScaryStories.MobileService.Entity.Entities;

namespace ScaryStories.MobileService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category:CustomEntity
    {
        public Category()
        {
            this.Stories = new HashSet<Story>();
        }
    
       
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
      
    
        public virtual ICollection<Story> Stories { get; set; }
    }
}
