//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScaryStories.MobileService.Entity.Entities;

namespace ScaryStories.MobileService.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Photo : CustomEntity
    {
        public Photo()
        {
            this.Stories = new HashSet<Story>();
        }
    
      
        public byte[] Image { get; set; }
        public byte[] Thumb { get; set; }
     
        public virtual ICollection<Story> Stories { get; set; }
    }
}
