//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScaryStories.MobileService.Entity.Entities;

namespace ScaryStories.MobileService.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Story : CustomEntity
    {
     
        public string CategoryId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public string SourceId { get; set; }
        public string PhotoId { get; set; }
       
        public Nullable<long> Likes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Source Source { get; set; }
    }
}
