//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScaryStories.MobileService.Entity.Entities;

namespace ScaryStories.MobileService.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Video : CustomEntity
    {
        public string Url { get; set; }
        public byte[] Thumb { get; set; }
        public string Text { get; set; }
     
        public string Name { get; set; }
        public string ChannalName { get; set; }
        public string SourceId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
